---
Name: goldfinch-cleaner
After:
  - '#campaignadmin'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Cleaner\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Goldfinch\Cleaner\Extensions\RemoveCampaignAdminExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Goldfinch\Cleaner\Extensions\RemoveAssetsExtension

SilverStripe\Control\Director:
  rules:
    'admin/campaigns': '->admin/'
    'admin/reports': '->admin/'
