---
Name: goldfinch-cleaner
After:
  - '#campaignadmin'
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Goldfinch\Cleaner\Extensions\RemoveCampaignAdminExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Cleaner\Extensions\SiteConfigExtension
